### ISSUE TITLE
This package should work in .txt files?

### ISSUE THREAD

**Issue by mcleary** [atom/language-hyperlink#2]
I use Atom in a MacOS 10.10. I have a .txt file with some links but the package seems to have no effect.
How I know it should be working?

**Comment by kevinsawicki** [comment]
Yup, it should be active for all text and markdown files as well as comments in code.

I'm going to close this out since it does appear to be working in text files in the current Atom release.

If you still see it, please comment with a screenshot and more details about what themes you are using, and what packages you have installed.
